operate/constants.py
operate/utils/gnosis.py

Fix: Handle orphaned transactions

---

operate/services/service.py

Pass the image_author when building the docker compose

fix: Pass image_author for building docker compose

---

operate/services/service.py

Backup env vars before building deployment.

Backup env vars

---

operate/quickstart/analyse_logs.py

fix: analyse logs

---

operate/services/manage.py
operate/services/protocol.py

fix: optimism fallback gas defaults

---

operate/constants.py
operate/services/utils/mech.py

added latest mech suport with MechMarketplace contracts

---

operate/services/protocol.py

added self with chain_type

---

operate/services/manage.py

Don't unstake if no funds on staking contract. This will prevent user from losing their spot on the contract.

Don't unstake if no funds on staking contract

---

operate/quickstart/run_service.py
operate/services/service.py
tests/test_services_service.py

fixed middleware migration issue

---

docs/api.md
operate/account/user.py
operate/cli.py
operate/utils/__init__.py
operate/wallet/master.py
tests/test_operate_cli.py
tests/test_services_manage.py

Update password using either existing password or BIP-39 seed phrase
* Fixes bug that didn't change password on wallets.
* Adds feature to change password based on seed phrase (mnemonic).

Update password using either existing password or BIP-39 seed phrase

---

operate/quickstart/claim_staking_rewards.py
operate/quickstart/reset_staking.py
operate/quickstart/run_service.py
operate/quickstart/stop_service.py
operate/quickstart/terminate_on_chain_service.py
operate/quickstart/utils.py
operate/services/manage.py

Feat: Support multiple agents from single `.operate`

---

pyproject.toml

Chore: Release `v0.2.3`

---

operate/quickstart/run_service.py

Fix (Quickstart): Remove non-ascii ∞

---

operate/ledger/profiles.py
operate/quickstart/reset_staking.py
operate/quickstart/run_service.py
operate/services/manage.py

Feat: Support custom staking contracts

---

operate/__init__.py
operate/cli.py
operate/quickstart/run_service.py
operate/services/manage.py
operate/services/protocol.py

Removing the agent_id check from staking mechanism

Remove agent_id check from staking mechanism

---

operate/ledger/profiles.py
operate/quickstart/run_service.py

Feat: QS Beta Expert 17 and 18

---

operate/ledger/profiles.py
operate/quickstart/run_service.py
pyproject.toml

Chore: Release `v0.2.4`

---

operate/services/manage.py
operate/services/protocol.py

Small comment on code

---

operate/services/manage.py
operate/services/service.py

fix: support for `mech-predict@v0.3.1`

---

pyproject.toml

chore: release `v0.2.6`

---

operate/ledger/profiles.py
operate/quickstart/run_service.py

Feat: Add supply/demand staking contracts for Mech

---

operate/services/manage.py
operate/services/protocol.py

Fix: `is_update` when switching `no_staking`

---

operate/quickstart/run_service.py
operate/quickstart/utils.py
pyproject.toml

Fix (Quickstart): Separate master safe funding requirement

---

operate/resource.py
tests/conftest.py
tests/test_operate_cli.py
tests/test_services_manage.py

- Rotating backup of resource files when saving.
- Clean up some tests.
Example:
```
ethereum.json.bak.0
ethereum.json.bak.1
ethereum.json.bak.2
ethereum.json.bak.3
ethereum.json.bak.4
```

Backup resource files

---

operate/resource.py

Fix resource.py

---

operate/resource.py
tox.ini

Fix backup resource

---

operate/wallet/master.py

Fixes a bug that allows override master wallet EOA file.

Fix master wallet creation

---

operate/quickstart/utils.py

Adjust the RPC validation for the new error message

Fix: RPC validation for Alchemy, Nodies, and Quicknode

---

operate/quickstart/run_service.py
operate/services/manage.py
pyproject.toml

Feat: Configurable priority mech address

---

operate/quickstart/run_service.py
operate/quickstart/utils.py
operate/services/manage.py

Refactor (Quickstart): Funding requirements logic

---

operate/services/manage.py
operate/services/protocol.py

Fixes the method `get_service_safe_owners` when the service hasn't been through a full minting-deployment cycle.

Fix get service safe owners

---

operate/services/manage.py

Fix: Priority mech misconfiguration from existing configs

---

operate/services/manage.py

Chore: Support any Agents.fun env-vars

---

operate/quickstart/claim_staking_rewards.py

Fix: Minor CLI fixes for claim-qs

---

.gitignore
operate/resource.py
tests/rw.py
tests/test_resource.py

Fix (LocalResource): Prevent corruption on killing

---

operate/services/health_checker.py

healthchecker fixes

---

operate/services/service.py

Fix: Volume mappings and env-vars in docker deployment

---

pyproject.toml

Chore: Bump version

---

operate/services/manage.py
poetry.lock
pyproject.toml

Fix: Refill requirement when `TERMINATED_BONDED`

---

operate/ledger/profiles.py
operate/quickstart/run_service.py
operate/services/manage.py

Feat: Dynamic defaults for priority mech in QS

---

operate/cli.py

Feat: Support daemon API with SSL

---

operate/services/agent_runner.py

meme-orrr agent runner moved to another repo

---

operate/bridge/providers/relay_provider.py
tests/test_bridge_bridge_manager.py

Fix Relay API  parameter

---

operate/services/service.py
operate/utils/ssl.py
pyproject.toml
tox.ini

Feat: Support SSL for agents HTTPS server

---

operate/utils/gnosis.py
pyproject.toml

Fix: Exclude L1 fees for Mode chain for draining

---

operate/services/deployment_runner.py
operate/services/manage.py

Fix: Trader's store persistence

---

operate/bridge/bridge_manager.py
operate/bridge/providers/native_bridge_provider.py
operate/bridge/providers/provider.py
operate/cli.py
operate/keys.py
operate/services/health_checker.py
operate/services/manage.py
operate/utils/gnosis.py
operate/wallet/master.py
tests/test_bridge_bridge_manager.py
tests/test_bridge_providers.py

Remove optional loggers

---

operate/constants.py
operate/services/deployment_runner.py

minor fixes and workarounds to make agent restart after sleep mode more stable

---

operate/keys.py
operate/quickstart/run_service.py
pyproject.toml
tests/conftest.py
tests/test_keys.py

Fix: Permissing error on windows in KeysManager

---

docs/api.md
operate/bridge/providers/relay_provider.py
pyproject.toml

Fix Relay provider

---

operate/services/manage.py
pyproject.toml

Adds the new mech variable: `MECH_TO_MAX_DELIVERY_RATE`

adds `MECH_TO_MAX_DELIVERY_RATE`

---

operate/services/service.py
pyproject.toml

* Updating the hash of the tools accuracy ranking for the traders
* Updating the column name for the tools accuracy requests field
- [X ] New feature (non-breaking change which adds functionality)

updating accuracy tools hash and new format

---

operate/keys.py
operate/services/manage.py
operate/services/protocol.py

Fix recovery module file permission issue

Fix recovery module file permission issue

---

docs/api.md
operate/constants.py
operate/services/health_checker.py
operate/services/service.py

Feat: Support `is_healthy` in healthcheck response

---

pyproject.toml

Fix: Dependencies alignment with open-autonomy

---

poetry.lock

chore: lock dependencies

---

docs/api.md
operate/cli.py
operate/constants.py
operate/ledger/profiles.py
operate/services/funding_manager.py
operate/services/manage.py
tests/conftest.py
tests/test_services_funding.py
tests/test_wallet_wallet_recovery.py

Funding v2 - flow 7 (Withdraw ALL funds from Agent to MasterSafe)

Funding v2 - flow 7 (Withdraw ALL funds from Agent to MasterSafe)

---

docs/api.md
operate/cli.py
tests/conftest.py
tests/test_services_funding.py

Funding v2 - flow 5 (User wants to add more funds to the Agent )

Funding v2 - flow 5 (User wants to add more funds to the Agent )

---

docs/api.md
operate/cli.py
operate/ledger/__init__.py
operate/ledger/profiles.py
operate/utils/gnosis.py
operate/wallet/master.py
tests/conftest.py
tests/test_services_funding.py

Funding v2 - flow 8 (Withdraw funds from MasterSafe & MasterEOA)

Funding v2 - flow 8 (Withdraw funds from MasterSafe & MasterEOA)

---

operate/cli.py

Feat: Support unattended mode for `quickstop`

---

operate/ledger/profiles.py
operate/quickstart/run_service.py
pyproject.toml

- Add `quickstart_beta_mech_marketplace_expert_1` and `quickstart_beta_mech_marketplace_expert_2`

Feat: Add QS beta MM expert 1 and 2

---

operate/services/agent_runner.py
pyproject.toml

Chore: Update `agent_runner` versions
